Card_0_0 = "Bridge Hit"
Card_0_1 = "Cargo Bay Hit"
Card_0_3 = "Direct Hit"
Card_0_4 = "Engine Room Hit"
Card_0_5 = "Engines Hit"
Card_0_6 = "Sickbay Hit"
Card_0_7 = "Weapon Systems Hit"
Card_0_45 = "Ace In The Hole"
Card_0_48 = "Never Say Die"
Card_0_54 = "Berlin"
Card_0_55 = "London"
Card_0_56 = "Moscow"
Card_0_57 = "Paris"
Card_0_58 = "Washington"
Card_0_72 = "Assault Cruiser"
Card_0_73 = "Assault Frigate"
Card_0_75 = "Behemoth"
Card_0_84 = "Swarm Frigate"

Card_0_0_Text = " "
Card_0_1_Text = " "
Card_0_3_Text = " "
Card_0_4_Text = " "
Card_0_5_Text = " "
Card_0_6_Text = " "
Card_0_7_Text = " "
Card_0_45_Text = "FIGHT: Make a starship power +3."
Card_0_48_Text = "FIGHT: Make a starship power +2 (or +4 if that starship is not damaged)."
Card_0_54_Text = " "
Card_0_55_Text = " "
Card_0_56_Text = "Flagship."
Card_0_57_Text = " "
Card_0_58_Text = " "
Card_0_72_Text = " "
Card_0_73_Text = " "
Card_0_75_Text = " "
Card_0_84_Text = " "

Card_Property_Power = "Power"
Card_Property_Structure = "Structure"

Card_Type_Damage = "Damage"
Card_Type_Effect = "Effect"
Card_Type_Starship = "Starship"


Error_AuthenticationRequired = "You must authenticate yourself in order to play Pinned Down."
Error_NotAllEnemyShipsAssigned = "You have to assign all of your ships to fight!"
Error_NotAllFightsResolved = "You have to resolve all fights first!"
Error_UnableToConntect = "Unable to connect to server.\r\n\r\nCheck http://pinneddown.de/server if you're sure you've done everything right!"


GameScreen_Button_EndTurnPhase = "End Turn Phase"
GameScreen_Button_Hint = "Help"

GameScreen_GameOver_Defeat = "DEFEAT!"
GameScreen_GameOver_Victory = "VICTORY!"
GameScreen_GameOver_EndGame = "End Game"

GameScreen_Hint_Assignment = "Assign your starships to enemy attackers by tapping one of your ships first, and an enemy ship after!"
GameScreen_Hint_Attack = ""
GameScreen_Hint_Fight = "Play effects to increase the power of your starships by tapping of your effects in hand first, and one of your ships after!\r\nResolve fights in order of your choice by tapping any of your assigned ships!"
GameScreen_Hint_Jump = ""
GameScreen_Hint_Main = "Tap a starship on your hand to deploy it for battle!\r\nTap and hold any hand card to show its details!\r\n"

GameScreen_Info_DistanceCovered = "Distance Covered:"
GameScreen_Info_TurnPhase = "Turn Phase:"
GameScreen_Info_Threat = "Threat:"

GameScreen_TurnPhase_Assignment = "Assignment"
GameScreen_TurnPhase_Attack = "Attack"
GameScreen_TurnPhase_Fight = "Fight"
GameScreen_TurnPhase_Jump = "Jump"
GameScreen_TurnPhase_Main = "Main"


LoginScreen_Connecting = "Connecting"
LoginScreen_Reconnect = "Reconnect"
LoginScreen_UnableToConnect = "Connecting"
LoginScreen_WaitingForPlayers = "Waiting For Players"